title: Multi Assets Brokers
description: A business home page starter template for Bootstrap 4 featuring marketing boxes and a full width image header.

baseurl: 
color-scheme: "#467187" # the scheme can be any HEX code like "#00aa55"

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - .sass-cache
collections:
  posts:
    title: Posts
    output: true
  reviews:
    title: Reviews
    output: true
    score: 5
  uploads:
    title: Uploads
    output: true
email: info@multiassetsbrokers.com