---
title: Multi Assets Brokers
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  reviews:
    title: Reviews
    output: true
    score: 5
  uploads:
    title: Uploads
    output: true
description: description
baseurl: https://multiassetsbrokers.com
color-scheme: "#467187"
sass:
  sass_dir: "/assets/css/_sass"
  style: compressed
include:
- _pages
exclude:
- ".sass-cache"
email: info@multiassetsbrokers.com
